from flask import Flask, request, jsonify, send_from_directory
import numpy as np
import json
import os
import sys
import requests

# --- CONFIG ---
# Explicitly set the folder to where this script is located
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_ID = "text-embedding-nomic-embed-text-v1.5"
LM_STUDIO_API_URL = "http://localhost:1234/v1/embeddings"

# These match the files generated by ingest.py
VECTOR_FILE = "golem_vectors.npy"
JSON_FILE = "golem_cortex.json"

# UPDATED: Matches your new repo filename
HTML_FILE = "index.html" 

app = Flask(__name__, static_folder=BASE_DIR)

print(f"\n🧠 PROJECT GOLEM SERVER")
print(f"   📂 Serving from: {BASE_DIR}")

# --- DIAGNOSTICS ---
# Check if files exist before starting
missing_files = []
if not os.path.exists(os.path.join(BASE_DIR, VECTOR_FILE)):
    missing_files.append(VECTOR_FILE)
if not os.path.exists(os.path.join(BASE_DIR, JSON_FILE)):
    missing_files.append(JSON_FILE)
if not os.path.exists(os.path.join(BASE_DIR, HTML_FILE)):
    missing_files.append(HTML_FILE)

if missing_files:
    print(f"   ❌ CRITICAL ERROR: Missing files in this folder:")
    for f in missing_files:
        print(f"      - {f}")
    
    # UPDATED: Points to the correct script name
    print("   👉 Did you run 'python ingest.py' successfully?") 
    
    if VECTOR_FILE in missing_files:
        print("   (The server cannot start without the vector matrix.)")
        sys.exit(1)
else:
    print(f"   ✅ Files Verified: Memory Matrix & Cortex Map found.")

# --- LOAD BRAIN ---
print(f"   ↳ Connecting to LM Studio at {LM_STUDIO_API_URL}...")
try:
    test_response = requests.get("http://localhost:1234/v1/models")
    test_response.raise_for_status()
    print(f"   ↳ ✓ Connected to LM Studio")
except requests.exceptions.RequestException as e:
    print(f"   ✗ Failed to connect to LM Studio. Make sure it's running on port 1234.")
    sys.exit(1)

print("   ↳ Loading Memory Matrix...")
memory_matrix = np.load(os.path.join(BASE_DIR, VECTOR_FILE))
# Normalize
norm = np.linalg.norm(memory_matrix, axis=1, keepdims=True)
memory_matrix = memory_matrix / norm

# --- HELPER FUNCTIONS ---
def get_embeddings(texts):
    """Get embeddings from LM Studio API."""
    response = requests.post(
        LM_STUDIO_API_URL,
        json={
            "model": MODEL_ID,
            "input": texts
        }
    )
    response.raise_for_status()
    data = response.json()
    # Sort by index to ensure correct order
    embeddings = sorted(data['data'], key=lambda x: x['index'])
    return np.array([item['embedding'] for item in embeddings])

# --- ROUTES ---

@app.route('/')
def root():
    # Force serve the specific HTML file
    return send_from_directory(BASE_DIR, HTML_FILE)

@app.route('/<path:filename>')
def serve_static(filename):
    return send_from_directory(BASE_DIR, filename)

@app.route('/query', methods=['POST'])
def query_brain():
    data = request.json
    text = data.get('query', '')
    if not text: return jsonify({"indices": []})

    print(f"🔎 Query: {text}")
    query_vec = get_embeddings(["Represent this query for retrieval: " + text])[0]
    
    scores = np.dot(memory_matrix, query_vec)
    top_indices = np.argsort(scores)[-50:][::-1] # increased to 50 for denser glow
    
    return jsonify({
        "indices": top_indices.tolist(),
        "scores": scores[top_indices].tolist()
    })

if __name__ == '__main__':
    print("   ✅ SYSTEM ONLINE: http://localhost:8000")
    app.run(port=8000)
