from flask import Flask, request, jsonify, send_from_directory
import numpy as np
import json
import os
import sys
import requests
import pickle
from rank_bm25 import BM25Okapi
from nltk.tokenize import word_tokenize
import nltk
from sentence_transformers import CrossEncoder

# --- CONFIG ---
# Explicitly set the folder to where this script is located
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_ID = "text-embedding-nomic-embed-text-v1.5"
LM_STUDIO_API_URL = "http://localhost:1234/v1/embeddings"

# These match the files generated by ingest.py
VECTOR_FILE = "golem_vectors.npy"
JSON_FILE = "golem_cortex.json"
UMAP_FILE = "golem_umap_model.pkl"

# UPDATED: Matches your new repo filename
HTML_FILE = "index.html" 

app = Flask(__name__, static_folder=BASE_DIR)

print(f"\n🧠 PROJECT GOLEM SERVER")
print(f"   📂 Serving from: {BASE_DIR}")

# --- DIAGNOSTICS ---
# Check if files exist before starting
missing_files = []
if not os.path.exists(os.path.join(BASE_DIR, VECTOR_FILE)):
    missing_files.append(VECTOR_FILE)
if not os.path.exists(os.path.join(BASE_DIR, JSON_FILE)):
    missing_files.append(JSON_FILE)
if not os.path.exists(os.path.join(BASE_DIR, HTML_FILE)):
    missing_files.append(HTML_FILE)

if missing_files:
    print(f"   ❌ CRITICAL ERROR: Missing files in this folder:")
    for f in missing_files:
        print(f"      - {f}")
    
    # UPDATED: Points to the correct script name
    print("   👉 Did you run 'python ingest.py' successfully?") 
    
    if VECTOR_FILE in missing_files:
        print("   (The server cannot start without the vector matrix.)")
        sys.exit(1)
else:
    print(f"   ✅ Files Verified: Memory Matrix & Cortex Map found.")

# --- LOAD BRAIN ---
print(f"   ↳ Connecting to LM Studio at {LM_STUDIO_API_URL}...")
try:
    test_response = requests.get("http://localhost:1234/v1/models")
    test_response.raise_for_status()
    print(f"   ↳ ✓ Connected to LM Studio")
except requests.exceptions.RequestException as e:
    print(f"   ✗ Failed to connect to LM Studio. Make sure it's running on port 1234.")
    sys.exit(1)

print("   ↳ Loading Memory Matrix...")
memory_matrix = np.load(os.path.join(BASE_DIR, VECTOR_FILE))
# Normalize
norm = np.linalg.norm(memory_matrix, axis=1, keepdims=True)
memory_matrix = memory_matrix / norm

# Load cortex data for BM25 and metadata
print("   ↳ Loading Cortex Data...")
with open(os.path.join(BASE_DIR, JSON_FILE), 'r') as f:
    cortex_data = json.load(f)

# Build BM25 index
print("   ↳ Building BM25 Index...")
nltk.download('punkt', quiet=True)
corpus = [node['text'] for node in cortex_data]
tokenized_corpus = [word_tokenize(doc.lower()) for doc in corpus]
bm25_index = BM25Okapi(tokenized_corpus)

# Load Cross-Encoder for re-ranking
print("   ↳ Loading Cross-Encoder Model...")
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

# Load UMAP model for query projection
print("   ↳ Loading UMAP Model...")
umap_model = None
umap_path = os.path.join(BASE_DIR, UMAP_FILE)
if os.path.exists(umap_path):
    with open(umap_path, 'rb') as f:
        umap_model = pickle.load(f)
    print("   ↳ ✓ UMAP model loaded")
else:
    print("   ⚠ UMAP model not found - query projection disabled")

# --- HELPER FUNCTIONS ---
def get_embeddings(texts):
    """Get embeddings from LM Studio API."""
    response = requests.post(
        LM_STUDIO_API_URL,
        json={
            "model": MODEL_ID,
            "input": texts
        }
    )
    response.raise_for_status()
    data = response.json()
    # Sort by index to ensure correct order
    embeddings = sorted(data['data'], key=lambda x: x['index'])
    return np.array([item['embedding'] for item in embeddings])

def reciprocal_rank_fusion(rankings_list, k=60):
    """Combine rankings using Reciprocal Rank Fusion."""
    fusion_scores = {}
    for rankings in rankings_list:
        for rank, (idx, _) in enumerate(rankings):
            fusion_scores[idx] = fusion_scores.get(idx, 0) + 1/(k + rank)
    return sorted(fusion_scores.items(), key=lambda x: x[1], reverse=True)

def get_cosine_results(query_vec, top_k=50):
    """Get results using cosine similarity."""
    scores = np.dot(memory_matrix, query_vec)
    top_indices = np.argsort(scores)[-top_k:][::-1]
    return [(idx, scores[idx]) for idx in top_indices]

def get_bm25_results(query_text, top_k=50):
    """Get results using BM25."""
    tokenized_query = word_tokenize(query_text.lower())
    scores = bm25_index.get_scores(tokenized_query)
    top_indices = np.argsort(scores)[-top_k:][::-1]
    return [(idx, scores[idx]) for idx in top_indices]

def rerank_with_cross_encoder(query_text, candidate_indices, top_k=50):
    """Re-rank top candidates using cross-encoder."""
    query_doc_pairs = [(query_text, cortex_data[idx]['text']) for idx in candidate_indices]
    ce_scores = cross_encoder.predict(query_doc_pairs)

    # Return top_k after re-ranking
    ranked = sorted(enumerate(ce_scores), key=lambda x: x[1], reverse=True)
    return [(candidate_indices[rank[0]], rank[1]) for rank in ranked[:top_k]]

def project_query_to_3d(query_vec):
    """Project query embedding to 3D space using UMAP."""
    if umap_model is None:
        return None
    try:
        query_3d = umap_model.transform(query_vec.reshape(1, -1))[0]
        return query_3d.tolist()
    except Exception as e:
        print(f"   ⚠ Query projection failed: {e}")
        return None

# --- ROUTES ---

@app.route('/')
def root():
    # Force serve the specific HTML file
    return send_from_directory(BASE_DIR, HTML_FILE)

@app.route('/<path:filename>')
def serve_static(filename):
    return send_from_directory(BASE_DIR, filename)

@app.route('/query', methods=['POST'])
def query_brain():
    data = request.json
    query_text = data.get('query', '')
    method = data.get('method', 'cosine')

    if not query_text:
        return jsonify({
            "indices": [],
            "scores": [],
            "method_breakdown": {},
            "query_position": None,
            "method": "none"
        })

    print(f"🔎 Query: {query_text} [{method}]")

    # Get query embedding
    query_vec = get_embeddings(["Represent this query for retrieval: " + query_text])[0]
    query_vec_normalized = query_vec / np.linalg.norm(query_vec)

    # Get results based on method
    if method == 'cosine':
        results = get_cosine_results(query_vec_normalized)
    elif method == 'bm25':
        results = get_bm25_results(query_text)
    elif method == 'cross_encoder':
        # Get top-50 from cosine first, then re-rank with cross-encoder
        cosine_results = get_cosine_results(query_vec_normalized, top_k=100)
        cosine_indices = [idx for idx, _ in cosine_results]
        results = rerank_with_cross_encoder(query_text, cosine_indices)
    elif method == 'hybrid':
        # Combine cosine + BM25 using RRF, optionally re-rank with cross-encoder
        cosine_results = get_cosine_results(query_vec_normalized, top_k=100)
        bm25_results = get_bm25_results(query_text, top_k=100)
        fused_results = reciprocal_rank_fusion([cosine_results, bm25_results])
        results = fused_results[:50]
    else:
        results = get_cosine_results(query_vec_normalized)

    # Extract indices and scores, convert to native Python types for JSON serialization
    result_indices = [int(idx) for idx, _ in results]
    result_scores = [float(score) for _, score in results]

    # Build method_breakdown showing which method ranked each result highest
    method_breakdown = {}
    if method == 'hybrid' or method == 'cosine':
        # Also compute BM25 for comparison
        cosine_results = get_cosine_results(query_vec_normalized, top_k=100)
        bm25_results = get_bm25_results(query_text, top_k=100)

        cosine_ranks = {idx: rank for rank, (idx, _) in enumerate(cosine_results)}
        bm25_ranks = {idx: rank for rank, (idx, _) in enumerate(bm25_results)}

        for idx in result_indices:
            cosine_rank = cosine_ranks.get(idx, 999)
            bm25_rank = bm25_ranks.get(idx, 999)
            best_method = 'cosine' if cosine_rank <= bm25_rank else 'bm25'

            method_breakdown[str(idx)] = {
                "cosine_rank": int(cosine_rank),
                "bm25_rank": int(bm25_rank),
                "best": best_method
            }

    # Project query to 3D space
    query_position = project_query_to_3d(query_vec)

    return jsonify({
        "indices": result_indices,
        "scores": result_scores,
        "method_breakdown": method_breakdown,
        "query_position": query_position,
        "method": method
    })

if __name__ == '__main__':
    print("   ✅ SYSTEM ONLINE: http://localhost:8000")
    app.run(port=8000)
